### ISSUE TITLE
Update vulnerable wrap-ansi dependency

### ISSUE THREAD

**Issue by Sindhura3** [oclif/plugin-help#310]
One of the packages: wrap-ansi  (3.0.0 - 6.1.0) depends on vulnerable versions of string-width and strip-ansi. Please merge [PR](https://github.com/oclif/plugin-help/pull/255), update dev depdencies, and do a release.

**Comment by radomirbosak** [comment]
Also this one: https://github.com/oclif/plugin-help/pull/293

**Comment by shavo007** [comment]
hi all +1 on this. its failing our security scanning currently due to this issue. thanks.

**Comment by radomirbosak** [comment]
Unfortunately, this wasn't resolved. Only `@types/wrap-ansi` was upgraded, not `wrap-ansi` itself.

**Comment by RodEsp** [comment]
Thanks @radomirbosak, you're totally right.
The PR for that is https://github.com/oclif/plugin-help/pull/293 but our automated tests aren't passing so it'll require a little more time to look into it.

**Comment by Swaagie** [comment]
@RodEsp correct me if wrong, but it seems that #293 failed on engine requirements (e.g. minimum node@12) and both GHA workflows as well as circle CI got updated more recently to only run against 12, 14 and latest. Might just take a simple action rerun to get tests to pass.

**Comment by RodEsp** [comment]
Hey @Swaagie, you're right that the GitHub actions are failing due to incorrect versions of node but the CircleCI tests have already been updated and are giving a different error.

Are you able to see the [CircleCI job logs](https://app.circleci.com/pipelines/github/oclif/plugin-help/984/workflows/6889878e-1466-4a35-ae98-1cc562023e14/jobs/3859/parallel-runs/0/steps/0-104)?

**Comment by Swaagie** [comment]
Yea I noticed that failure as well. I suspect this requires an update to the `.mocharc.json` config, see https://github.com/mochajs/mocha/issues/4726. [These options are not well documented yet](https://github.com/mochajs/mocha-examples/issues/47) I'm happy to make an independent PR that fixes this.

**Comment by Swaagie** [comment]
Actually the real issue here is that `wrap-ansi>8` [moved to only expose ESM](https://github.com/chalk/wrap-ansi/releases/tag/v8.0.0). If this plugins aims to consume this major version it should change `require('wrap-ansi')` to `import ... from 'wrap-ansi'`. That change likely has larger implications though. 

According to the vulnerability audit using `ansi-regex>=5.0.1` should be good. Going to make a PR to use `wrap-ansi@7` as that depends on `strip-ansi@6` which use the designated version: https://github.com/chalk/strip-ansi/blob/6.0.1/package.json#L47

**Comment by Swaagie** [comment]
See https://github.com/oclif/plugin-help/pull/321
